### ISSUE TITLE
feat: Windows build signing

### ISSUE THREAD

**Issue by dacoaster** [dacoaster/yattie#11]
Procure a cert and setup Windows build signing to get rid of security warnings on download.

**Comment by parwalrahul** [comment]
Much needed; I was about to raise this. 

Especially in restricted environments like office; this issue makes it hard (and sometimes impossible) to use.

**Comment by dacoaster** [comment]
I've begun the process of getting validated for one.  Hopefully it doesn't take too long.

**Comment by parwalrahul** [comment]
@dacoaster Please share your twitter or linkedin handle for connection?

**Comment by dacoaster** [comment]
I don't use any social media really.  I was thinking about setting up a Slack or some forums for YATTIE though.  Any thoughts?  Also, feel free to reach out via email - david@rocksteady.technology.

**Comment by parwalrahul** [comment]
I feel Discord would be a better option for communities in the long run unless you want to go for a paid plan. I see some communities already migrating from Slack to Discord.

Check out the comparison here: https://orbit.love/blog/slack-vs-discord-vs-discourse

**Comment by dacoaster** [comment]
@parwalrahul  - This should be fixed in [v0.5.4](https://github.com/dacoaster/yattie/releases/tag/v0.5.4). Please check it out!
