### ISSUE TITLE
bug: Sign in with Jira gives network error

### ISSUE THREAD

**Issue by parwalrahul** [dacoaster/yattie#12]
# Bug Report

**Platform:**

Win 10

**YATTIE version:**

0.5

**Current behavior:**

![image](https://user-images.githubusercontent.com/12759282/215423045-e45b3dcc-f844-43c0-ac4a-d316b1b10d14.png)

**Other information:**

Tried thrice, and there is no network issue on the test machine. It is well connected to the internet. Let me know if we save some logs on the host machine for such errors. I can share them for detailed debugging.

**Comment by dacoaster** [comment]
@parwalrahul - With some tweaks to the config, this is now working in [v0.5.1](https://github.com/dacoaster/yattie/releases/tag/v0.5.1) (I tested the final artifacts on Win11 and Ubuntu).

Please take a look!
