### ISSUE TITLE
bug: 'Save session' window opens multiple times

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#15]
# Bug Report

**Platform:**

Windows

**YATTIE version:**

0.5.3

**Current behavior:**
![save session](https://user-images.githubusercontent.com/76529337/222659653-b397f405-862d-4736-9057-2062d32b07d2.png)

When we save the session from the File option, the 'Save session' window opens 6 times.
**Steps to reproduce:**

File --> Save session

**Comment by dacoaster** [comment]
@narkhedeshubham -

I can't reproduce this on either Linux or a fresh Windows 11 VM.

Can you provide more information about your setup?

**Comment by narkhedeshubham** [comment]
Processor: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
Installed Ram: 16.0 GB
System Type: 64-bit operating system, x64-based processor
Edition: Windows 10 Enterprise
Version: 21H2

**Comment by dacoaster** [comment]
@narkhedeshubham -

Can you share further reproduction steps?  Is this on Quick Test or an Exploratory Session?  How large is the session?  (How many pieces of evidence?)  Does it always happen or only under specific circumstances?  If you do save the session, does it successfully create the file?  If so, can you share that file?

**Comment by narkhedeshubham** [comment]
https://user-images.githubusercontent.com/76529337/223792921-62daa5bd-123a-41e6-a132-d13ad05e2cc6.mp4


I tried to reproduce it at my end so it is for both the test, 'Quick test' and 'Exploratory Session' when we start session --> end session and save the summary, then we go to Export session report page and from their when we try to save the session from the File option we get 2 save session window. Again when we resume the session and try to save it from the File --> Save session, 3 save session window get displayed and when we repeat the same scenario every time the save session window get's increase by one window.

**Comment by dacoaster** [comment]
That's great troubleshooting @narkhedeshubham - I can reproduce it now.

I will fix this and include it with the next release.

**Comment by dacoaster** [comment]
@narkhedeshubham - This is fixed in v0.5.5.

Thank you again for your report!
