### ISSUE TITLE
feat: Provide Sub Categories for Observations

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#16]
# Feature Request

**Describe the Feature Request**

When reporting a bug we select what kind of observation it is, like whether is it a problem or question, or suggestion, when the user selects the problem option we can also categorize some common problems\bugs in the drop-down box like is it a UX problem or functional problem, or logic problem, etc.

**Comment by dacoaster** [comment]
@narkhedeshubham -

Thank you for the feature request!

There is something in the tool which allows for more flexibility around labeling that may work for your use case.

You can create arbitrary tags for each piece of evidence to keep track of whatever is most important for you:
![tags](https://user-images.githubusercontent.com/54721212/222812138-72a85b61-3482-41c6-baef-3e535b51fe27.gif)

These are then reflected in the summary document as well:
![image](https://user-images.githubusercontent.com/54721212/222812039-c897910c-fd89-45f4-a940-5424226688c8.png)

Please let me know if that accomplishes what you need.

**Comment by parwalrahul** [comment]
I like this tags feature. Thanks for informing about it :)

**Comment by dacoaster** [comment]
Thanks @parwalrahul!  How are you liking the tool?

@narkhedeshubham - Does the tags feature accomplish what you were looking for?

**Comment by narkhedeshubham** [comment]
Yes, it's helpful for me. Thanks!

**Comment by dacoaster** [comment]
Thank you @narkhedeshubham - if you are enjoying the tool, please do consider taking a few minutes to fill out [our survey](https://yatt.ai/yattie-survey) and telling your friends/colleagues about it!
