### ISSUE TITLE
bug: External connections from the settings menu don't work

### ISSUE THREAD

**Issue by Bhaveshkumar-Sukhdeve** [dacoaster/yattie#19]
# Bug Report

**Platform:**

Windows 11

**YATTIE version:**

[v0.5.4](Beta)
![External Connection Link Issue](https://user-images.githubusercontent.com/127382743/224232573-b04c5c61-6407-4414-9a6f-5b4d0e8f936d.png)

**Current behavior:**

Both the external links are not working, nothing is happening after clicking on them.

**Expected behavior:**

The link should work and redirect user to connect with JIRA instance/TestRail instance

**Steps to reproduce:**

1. Click on File
2. Click on App settings
3. Click on Connections
4. Try to click on both external connection links

**Other information:**

If the links are not working because of some preconditions then after clicking on them should display some message.

**Comment by Bhaveshkumar-Sukhdeve** [comment]
@dacoaster  Thanks for the detailed explanation, I will surely retest this in v0.6.0

**Comment by dacoaster** [comment]
Fixed in #48

**Comment by dacoaster** [comment]
Removed/fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0)

**Comment by Bhaveshkumar-Sukhdeve** [comment]
@dacoaster It is resolved in [v0.6.0]. Thanks
