### ISSUE TITLE
bug: There is no option to for cancel, after the user accidentally press the End session. 

### ISSUE THREAD

**Issue by anakhavviswanathan** [dacoaster/yattie#22]
# Bug Report

**Platform:**Windows

**YATTIE version:**0.5.3.0

**Current behavior:** if the user accidentally presses the **End session**  button then the user has any option to **cancel** that 
                                  user needs to save the session and resume the test session. 

**Expected behavior:**it would be more convenient to **cancel or close** option.

https://user-images.githubusercontent.com/92415365/225536215-8f14d2cb-a9b7-45f3-bc54-6de8cbb04a55.mp4

**Other information:**

**Comment by dacoaster** [comment]
Thank you for the report @anakhavviswanathan.  I already had this in my personal notes as well, so I appreciate you filing the bug.  We'll make sure that gets added.

**Comment by dacoaster** [comment]
Fixed in #48

**Comment by dacoaster** [comment]
@anakhavviswanathan - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
