### ISSUE TITLE
bug: After switching into the Dark Mode the font is not visible.

### ISSUE THREAD

**Issue by anakhavviswanathan** [dacoaster/yattie#24]
# Bug Report

**Platform:**Windows

**YATTIE version:** 0.5.5.0

**Current behavior:** if user select dark mode the font color remains the same as the bright color. so that the page is not readable.

**Expected behavior:** The font **color needs to change if we switch to dark mode.**

**Steps to reproduce:**  **File-->App Settings-->Appearance -->Darak mode**

**Related code:**

<img width="402" alt="Screenshot_8" src="https://user-images.githubusercontent.com/92415365/225601592-e91e9210-2f5e-49b3-95b4-f9bde82cb852.png">

**Comment by dacoaster** [comment]
Thanks for the bug report @anakhavviswanathan.  This one looks like it was just missed in the recent dark mode improvements.  I'll make sure it's fixed in the next minor release.

**Comment by dacoaster** [comment]
Fixed in #48

**Comment by dacoaster** [comment]
@anakhavviswanathan - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
