### ISSUE TITLE
bug: The Report feature is not showing.

### ISSUE THREAD

**Issue by anakhavviswanathan** [dacoaster/yattie#26]
# Bug Report

**Platform:** Windows

**YATTIE version:** 0.5

**Current behavior:**The report feature is not showing anything.

**Expected behavior:** the report feature needs to show the report settings

**Steps to reproduce:** App settings --> Report 

<img width="402" alt="Screenshot_9" src="https://user-images.githubusercontent.com/92415365/225604455-059df9d3-f31b-479c-b922-7da80f27b4a4.png">

**Comment by dacoaster** [comment]
@anakhavviswanathan, thank you for the report.  This is an error with the most recent code pushed.  It will be updated in the next minor release.

**Comment by dacoaster** [comment]
Fixed in #48

**Comment by dacoaster** [comment]
@anakhavviswanathan - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
