### ISSUE TITLE
feat: Add an "About" page which includes the app version number.

### ISSUE THREAD

**Issue by anakhavviswanathan** [dacoaster/yattie#27]
# Feature Request

**Describe the Feature Request** The app should show the version that we are using.

**Describe Preferred Solution** The version should specify.

**Comment by dacoaster** [comment]
@anakhavviswanathan, I have adding a "About" page in the drop down menu.  I'm going to update the title here to reflect that and will try to add it in one of the upcoming releases.

**Comment by dacoaster** [comment]
Fixed in #48

**Comment by dacoaster** [comment]
@anakhavviswanathan - Added in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
