### ISSUE TITLE
bug: All Edit features are not working as expected.

### ISSUE THREAD

**Issue by anakhavviswanathan** [dacoaster/yattie#29]
# Bug Report

**Platform:** Windows

**YATTIE version:** v5

**Current behavior:** The all Edit feature does not make any changes in while we are writing.

**Expected behavior:** It needs to edit while we are writing to our system.

**Steps to reproduce:** start session-->edit

https://user-images.githubusercontent.com/92415365/225608685-48a84622-909e-4cfc-9920-6b19efe8d0b6.mp4

**Comment by dacoaster** [comment]
Fixed in #48

**Comment by dacoaster** [comment]
@anakhavviswanathan - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
