### ISSUE TITLE
bug: Error Popup on Installation in Windows 11 (.exe)

### ISSUE THREAD

**Issue by parwalrahul** [dacoaster/yattie#3]
# Bug Report

**Platform:**

Windows 11

**YATTIE version:**

0.4.1

**Current behavior:**

Installing the .exe gives fail JS error.

App opens up after closing this popup.

![image](https://user-images.githubusercontent.com/12759282/213937119-8ba2942d-23bb-4360-ab3a-a9e747b92e43.png)

**Comment by dacoaster** [comment]
@parwalrahul -

That file was moved in the upcoming build we're working on, so I pushed a hotfix to fix this sooner.  Please checkout release [v0.4.2](https://github.com/dacoaster/yattie/releases/tag/v0.4.2).

With this new build I was able to install the .exe on a Windows 11 VM without issue.

**Comment by parwalrahul** [comment]
Retested on v0.4.2 and this issue is fixed now. Thanks :)
