### ISSUE TITLE
bug: Color of application changes when adding emojis in notes

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#32]
# Bug Report

**Platform:**

Windows 10

**YATTIE version:**

v0.5.5

**Current behavior:**

Application color changes when emojis are added to notes.

**Steps to reproduce:**

1. Start a quick or exploratory test.
2. Goto Notes section.
3. Enter any emoji.

![Screenshot_2](https://user-images.githubusercontent.com/76529337/228145927-76ff276d-3c3b-4264-beec-3e9091d9e1f7.png)

**Comment by dacoaster** [comment]
This is a weird one.  I'll get this fixed in the next release @narkhedeshubham.

**Comment by dacoaster** [comment]
@narkhedeshubham - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
