### ISSUE TITLE
bug: The End session popup continues to appear 

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#35]
# Bug Report

**Platform:**

Windows 10

**YATTIE version:**

v0.5.5

**Current behavior:**

The user continues to see the End session pop-up when the user opens the New session from the file menu

**Expected behavior:**

The End session pop-up should be closed if the user clicks on the New session. or the user should get some reminder to perform an action on the pop-up and then proceed.

**Steps to reproduce:**

1. New exploratory test
2. Start session
3. Select the screen
4. Stop session(do not click on pop-up action buttons)
5. File 
6. New session

https://user-images.githubusercontent.com/76529337/228506054-720a6f7f-999c-4273-a715-8d76f690546b.mp4

**Comment by dacoaster** [comment]
Thank you for the report @narkhedeshubham!

**Comment by dacoaster** [comment]
@narkhedeshubham - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
