### ISSUE TITLE
bug: Test details doesn't reset.

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#36]
# Bug Report

**Platform:**

Windows 10

**YATTIE version:**

v0.5.5

**Current behavior:**

The test details are not cleared when the user resets the session.

**Expected behavior:**

The test details should be cleared when the user resets the session.

**Steps to reproduce:**

1. New Exploratory session
2. Enter the title and set the time limit
3. Start the session
4. Select the screen
5. File menu
6. Reset the session
7. Click Confirm
8. Observe the test details.

https://user-images.githubusercontent.com/76529337/228737120-8a328f8b-fe18-4a91-98aa-7ce956f45cc0.mp4

**Comment by dacoaster** [comment]
@narkhedeshubham - This behavior is intentional but needs better documentation.
 
 "Reset Session" is for resetting the current session to the beginning.  If you'd like to clear all details, you should use "New Session".

**Comment by narkhedeshubham** [comment]
@dacoaster - But the time limit is not applicable once you reset the session and start it again. It will show you what time limit you have set before but it's not applicable need to re-enter it.
