### ISSUE TITLE
bug: Flow of quick test is affecting the exploratory session.

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#37]
# Bug Report

**Platform:**

Windows 10

**YATTIE version:**

v0.5.5

**Current behavior:**

When the user starts the quick test and goes back to the home page and selects the new exploratory test then the flow of the exploratory test is getting changed the user can’t see the test details page to fill in the details. The user directly gets the window selection pop-up.

**Expected behavior:**

After a Quick test if the User opens the new exploratory session it should not get affected.

**Steps to reproduce:**

1. Start a Quick test.
2. Select the screen
3. Go Back
4. Start a New exploratory session
5. Compare the exploratory session flow before opening the quick test and after opening the quick test. 

The actual flow of the exploratory session:

https://user-images.githubusercontent.com/76529337/228741396-2b3171c4-1190-4e65-ad3c-f2b06d5f4a6c.mp4

Exploratory session after a quick test:

https://user-images.githubusercontent.com/76529337/228741503-585cfe77-6be6-4da1-94c9-6ee5fb75f1cb.mp4

**Comment by dacoaster** [comment]
I had noticed some unusual behavior here as well.  Thank you for the report @narkhedeshubham!  We'll get this fixed.

**Comment by dacoaster** [comment]
@narkhedeshubham - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
