### ISSUE TITLE
bug: Emoji panel doesn't collapse

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#38]
# Bug Report

**Platform:**

Windows 10

**YATTIE version:**

v0.5.5

**Current behavior:**

Emoji panels do not collapse after an emoji is entered, on the export report page.

**Expected behavior:**

The Emoji panel should collapse when the user enters the emoji.

**Steps to reproduce:**

Quick test or new exploratory session

1. Start session
2. Do anyone action(Screenshot, video or note).
3. End the session
4. Add the emoji to the image.

![emoji](https://user-images.githubusercontent.com/76529337/228753033-3ef1a3b0-936c-4079-8759-fc9aad1b19e6.png)

**Comment by dacoaster** [comment]
Validated.  Hopefully we can get this in one of the next few minor releases.

**Comment by dacoaster** [comment]
@narkhedeshubham - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
