### ISSUE TITLE
bug: Sign in with Jira & YATT does not work

### ISSUE THREAD

**Issue by parwalrahul** [dacoaster/yattie#4]
# Bug Report

**Platform:**

Win 11

**YATTIE version:**

0.4.2

**Current behavior:**

Link not responsive

![image](https://user-images.githubusercontent.com/12759282/213975883-6e69bc37-2a3a-4ad5-bcc0-2cf3424a5776.png)

**Comment by dacoaster** [comment]
@parwalrahul - Please check out [v0.5.0](https://github.com/dacoaster/yattie/releases/tag/v0.5.0) for a first draft of the JIRA integration.

And thank you for all of your bug reports!
