### ISSUE TITLE
bug: PDF does not retain text formatting

### ISSUE THREAD

**Issue by davisonalves** [dacoaster/yattie#41]
# Bug Report

**Platform: Windows**

**YATTIE 0.5.5:**

**Current behavior: PDF does not retain text formatting**

When exporting a test session, extracting and opening the pdf, in the charter tab it is possible to view the text without any formatting

**Expected behavior: I would like the text to be formatted like I did in the app**

**Snapshots:**
YATTIE
![image](https://user-images.githubusercontent.com/53572219/228926907-43ed2185-c4ac-44c4-9974-cf277ae51489.png)

PDF
![image](https://user-images.githubusercontent.com/53572219/228927080-eb96df8d-8927-4e47-8a87-018083420f8d.png)

**Comment by dacoaster** [comment]
Thank you for the report @davisonalves - I'm already looking to give some attention to the reporting functionality in one of the next two releases, so I'll make sure to include this.

**Comment by dacoaster** [comment]
@davisonalves - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
