### ISSUE TITLE
bug: Adding more checklists is not possible after adding some

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#42]
# Bug Report

**Platform:**

Windows 10

**YATTIE version:**

v0.5.5

**Current behavior:**

When the user adds some checklist the "Add another checklist" button gets hidden behind the frame and is not able to scroll till that button.
 
**Expected behavior:**

Above the application frame, the "Add another checklist" button should be locked.

**Steps to reproduce:**

1. Files.
2. App Settings.
3. Checklist.
4. Try adding multiple checklists.

![checklist](https://user-images.githubusercontent.com/76529337/229114632-0ad8ad19-ba52-4aaf-bb53-2fb76528f72d.png)

**Comment by dacoaster** [comment]
Great catch! Thank you @narkhedeshubham

**Comment by dacoaster** [comment]
@narkhedeshubham - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!
