### ISSUE TITLE
bug: After switching into the Dark Mode, "Add reaction..." button is almost not visible

### ISSUE THREAD

**Issue by mMARUF** [dacoaster/yattie#43]
# Bug Report

**Platform:**
MacOS Ventura 13.3

**YATTIE version:**
0.5.50

**Current behavior:**
After switching to the dark mode, in the Screenshot dialog – the “Add reaction…” button is almost not visible. The button almost gets disappeared with the dark background.

**Expected behavior:**
After switching to the dark mode, in the Screenshot dialog – the “Add reaction…” button should be perfectly visible

**Steps to reproduce:**
1. Open YATTIE
2. Switch to dark mode
3. Create a new session
4. Press on Screenshot button
5. Then the screenshot - dialog opens
6. In the Screenshot dialog – the “Add reaction…” button is almost not visible. The button almost gets disappeared with the dark background.

**Attachment(s):**
![Screenshot 2023-04-07 at 2 49 22 PM](https://user-images.githubusercontent.com/45368054/230578084-fe18bbb0-1d89-48ad-9a7d-56db30dbc575.png)

**Comment by dacoaster** [comment]
@mMARUF - Thank you for the report!  This looks like it was an oversight.  I'll get it fixed in the upcoming release. (v0.6.0)

**Comment by dacoaster** [comment]
@mMARUF - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!

**Comment by mMARUF** [comment]
Looks Ok.
