### ISSUE TITLE
bug: elements on 'Save current progress' dialog is not readable on dark mode

### ISSUE THREAD

**Issue by mMARUF** [dacoaster/yattie#44]
# Bug Report

**Platform:**
MacOS Ventura 13.3

**YATTIE version:**
0.5.50

**Current behavior:**
elements on 'Save current progress' dialog is not readable on dark mode.
a) **'Save current progress'** text is almost not readable.
b) **Cancel** - button becomes white and the text of the button is not visible. 

**Expected behavior:**
After switching to the dark mode, elements on 'Save current progress' dialog should be visible.

**Steps to reproduce:**
1. Open YATTIE
2. Switch to dark mode
3. Create a new session
4. Press on **"New Session Button"** button again
5. Then the **'Save current progress'** dialog will open
6. elements on **'Save current progress'** dialog is not readable on dark mode.

**Attachment(s):**
<img width="580" alt="Screenshot 2023-04-07 at 11 48 39 PM" src="https://user-images.githubusercontent.com/45368054/230654681-5918b231-00fc-4590-a517-97a7fdbd6e12.png">

**Comment by dacoaster** [comment]
@mMARUF - Thank you for this report as well!  This was also an oversight while implementing dark mode.  I'll get it fixed in the upcoming release. (v0.6.0)

**Comment by dacoaster** [comment]
@mMARUF - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!

**Comment by mMARUF** [comment]
The Discard button is almost the same as the dialog background, which makes it harder to separate from the dialog background.
