### ISSUE TITLE
bug: Title - field pointer is in purple color and unable to see in dark mode

### ISSUE THREAD

**Issue by mMARUF** [dacoaster/yattie#45]
# Bug Report

**Platform:**
MacOS Ventura 13.3

**YATTIE version:**
0.5.50

**Current behavior:**
Title – field pointer is in purple color and unable to see in dark mode

**Expected behavior:**
Title – field pointer should be in white color so that users can see perfectly

**Steps to reproduce:**
1. Open YATTIE
2. Switch to dark mode
3. Create a new exploratory session
4. Select the Title field
5. Observe the **Title** field pointer
6. The title field pointer is in purple color. That is why it is very hard to see that the **Title** field is selected

**Attachment(s):**
<img width="496" alt="Screenshot 2023-04-10 at 5 39 46 PM" src="https://user-images.githubusercontent.com/45368054/230895063-83424277-aaea-4b91-8350-8fb0051812fc.png">

**Comment by dacoaster** [comment]
This has been fixed in the upcoming release.

**Comment by dacoaster** [comment]
@mMARUF - Fixed in [v0.6.0](https://github.com/dacoaster/yattie/releases/tag/v0.6.0) please check it out!

**Comment by mMARUF** [comment]
Looks fine
