### ISSUE TITLE
bug: Yattie Survey Link is Broken

### ISSUE THREAD

**Issue by parwalrahul** [dacoaster/yattie#5]
# Bug Report

This link is mentioned in the readme docs.

https://yatt.ai/yattie-survey

![image](https://user-images.githubusercontent.com/12759282/213977351-ac3aab40-db9c-4ec5-8293-ac132c49d7ab.png)

**Comment by dacoaster** [comment]
This page was taken down for a redesign yesterday evening.  It will hopefully be back up today or tomorrow.

In the meantime, if you'd like to take the survey (and your feedback is very much appreciated!), you can do so directly [here](https://docs.google.com/forms/d/e/1FAIpQLSczuKpo5yAKOzpikfY_G01lWGTyG9E2GJMeStOHRCOE6M3ZMw/viewform?usp=sf_link).

Also,thank you for all of the bug reports!  It's helpful to add these to the list of things we're knocking out as we get progressively more stable releases.

**Comment by dacoaster** [comment]
This link is fixed!

**Comment by parwalrahul** [comment]
![A3F80F84-2A4C-4126-B70C-CD02A96AD76B](https://user-images.githubusercontent.com/12759282/214210183-92365bb6-73bd-43e9-9939-c018169a305d.png)

Form link has access issues.

**Comment by dacoaster** [comment]
Thank you for your persistence @parwalrahul - I have now marked it as public.  Please try again if you would be so kind!
