### ISSUE TITLE
bug: Difficulty in Finding Specific Video from PDF in Video Folder

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#50]
# Bug Report

**Platform:**

Windows 10

**YATTIE version:**

v0.6.0

**Current behavior:**

Users are finding it difficult to locate a specific video from a PDF document in the video folder. This behavior is unexpected and negatively impacts the user experience.

**Expected behavior:**

 Users should be able to easily locate a specific video from a PDF document in the video folder.

**Steps to reproduce:**

Record a session with 4-5 videos -> Export the report -> Observe the PDF and video folder.

**Comment by dacoaster** [comment]
@narkhedeshubham - Thank you for the report.

When trying to find the videos, what are you trying to do with them?  Attach them to a JIRA ticket or something like that?

**Comment by dacoaster** [comment]
@narkhedeshubham - Following up here.

**Comment by narkhedeshubham** [comment]
I am trying to export the report to the local machine where we get a '.zip'  file, where it's challenging to find the videos.
