### ISSUE TITLE
bug: Mindmap button from menu tray during quick test opens the dev tools

### ISSUE THREAD

**Issue by parwalrahul** [dacoaster/yattie#6]
# Bug Report

**Platform:**

Win 11

**YATTIE version:**

0.4.2

**Current behavior:**

Click on the Mindmap button from the menu tray during a quick test opens the dev tools.

P.S. Direct bug so not doing detailed reporting. Let me know if you need detailed steps. Hopefully not!

**Comment by dacoaster** [comment]
This will also be in the next release (v0.4.3 or v0.5.0).  I will update here when it's released.
