### ISSUE TITLE
bug: Help options from top menu tray on landing page do not work nor redirects anywhere.

### ISSUE THREAD

**Issue by parwalrahul** [dacoaster/yattie#7]
# Bug Report

**Platform:**

Win 11

**YATTIE version:**

0.4.2

**Comment by dacoaster** [comment]
I've added this to the next release for this week.  (It will either be v0.4.3 or v0.5.0 depending on if the JIRA login work gets finished before the rest of the enhancements we want to ship.)

I'll update the thread here when it's done.

**Comment by dacoaster** [comment]
Fixed in [v0.4.3](https://github.com/dacoaster/yattie/releases/tag/v0.4.3).
