### ISSUE TITLE
bug: Unable to submit Jira Cloud issues

### ISSUE THREAD

**Issue by galactidev** [dacoaster/yattie#73]
# Bug Report

**Platform:**

macOS Ventura 13.4
Jira Cloud

**YATTIE version:**

v0.8.0

**Current behavior:**

After logging in with Jira, when attempting to submit a bug or any issue from YATTIE, the form refreshes without actually creating an issue in Jira. No success or error response.

**Expected behavior:**

When submitting the Create a New Issue form, the issue should be created in Jira with a success response, or an error response if unsuccessful.

**Steps to reproduce:**

1. Login with Jira Cloud
2. Start a test session
3. Click the 'Create a New Issue' button
4. Select a project and issuetype
5. Populate the desired fields on the form
6. Click the 'Export' button to submit

![YATTIE_Jira_bug](https://github.com/dacoaster/yattie/assets/132780105/31651454-3600-41a2-b6b8-41812027db53)

**Comment by dacoaster** [comment]
Fixed in v0.9.1
