### ISSUE TITLE
bug: Unable to Copy / Paste text in fields

### ISSUE THREAD

**Issue by galactidev** [dacoaster/yattie#74]
# Bug Report

**Platform:**

macOS Ventura 13.4

**YATTIE version:**

v0.8.0

**Current behavior:**

Unable to copy and paste throughout the app, either via right click or keyboard shortcuts (cmd+c cmd+v). Unable to copy text within or outside fields. Unable to paste within any fields. This makes it particularly difficult to copy API keys over for integrations. Right click context menu doesn't appear at all (though this might actually be by design).

**Expected behavior:**

All fields should accept the ability to copy / paste. Should also be able to copy text outside of fields (e.g. notes already taken, timer, general text across the app).

**Steps to reproduce:**

Attempt to copy and paste either within the app or from an external app to YATTIE fields.

**Other information:**

Checked to see if it was specific to macOS security settings on this device, and the privileges are set properly.

**Comment by dacoaster** [comment]
Fixed in v0.9.1
