### ISSUE TITLE
bug: File > New Session does not works. 

### ISSUE THREAD

**Issue by parwalrahul** [dacoaster/yattie#9]
# Bug Report

**Platform:**

Win

**YATTIE version:**

0.4.3

**Current behavior:**
![image](https://user-images.githubusercontent.com/12759282/214675164-c69d1f18-274e-47bf-97e5-51c621e33bad.png)

**Comment by dacoaster** [comment]
@parwalrahul -

The "New Session" option should do two things - clear any current session going on by resetting all of the data, and redirect you to the test charter page.

Currently, it does the former and not the latter.  (You can test this by selecting it while in an active test.)

I've got the redirect added back in the next release (v0.5.0).  I will ping here when it's updated.

**Comment by dacoaster** [comment]
@parwalrahul - This should be working in [v0.5.0](https://github.com/dacoaster/yattie/releases/tag/v0.5.0).
